"""
Django settings for student_test_platform_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


SECRET_KEY = 'django-insecure-n1+d7h2*3+-ob63*jxzqqi#gzk*4&#x3d&3=muidb02z+8-84^'


DEBUG = True


AUTH_USER_MODEL = 'users.StudentProfile' # [cite: 14] Bu qatorni qo'shing

# Media fayllar sozlamalari (rasmlar, PDFlar uchun)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login URL (foydalanuvchi tizimga kirmagan bo'lsa qayerga yo'naltirish)
LOGIN_URL = 'login' # Siz keyinchalik 'login' nomli URL yaratasiz
LOGIN_REDIRECT_URL = 'home' # Tizimga kirgandan keyin qayerga yo'naltirish (masalan, home sahifaga)
LOGOUT_REDIRECT_URL = 'login' # Tizimdan chiqqandan keyin qayerga yo'naltirish


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users', # Yangi ilova
    'tests', # Yangi ilova
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'student_test_platform_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_test_platform_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uz-uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# student_test_platform_project/settings.py

# ...
# student_test_platform_project/settings.py faylida

# ... (faylning yuqori qismi)

# Login URL (foydalanuvchi tizimga kirmagan bo'lsa qayerga yo'naltirish)
LOGIN_URL = 'login' # Bu users/urls.py faylida nomlangan 'login' URL ga mos keladi
LOGIN_REDIRECT_URL = 'test_list' # <<< ENG MUHIM O'ZGARISH: Testlar ro'yxatiga yo'naltiramiz
LOGOUT_REDIRECT_URL = 'login' # Tizimdan chiqqandan keyin 'login' sahifasiga yo'naltiramiz

# ... (faylning qolgan qismi)

# Quyidagi takrorlangan qatorlarni O'CHIRING, agar ular mavjud bo'lsa:
# LOGIN_URL = '/users/login/'
# LOGIN_REDIRECT_URL = '/home/'

