# Generated by Django 5.2.1 on 2025-05-28 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Javob varianti matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javobmi?")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='tests.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test sarlavhasi')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='test_pdfs/', verbose_name='Test PDF fayli')),
                ('num_questions', models.IntegerField(choices=[(20, '20 savol'), (30, '30 savol')], default=20, verbose_name='Savollar soni')),
                ('open_time', models.DateTimeField(verbose_name='Ochilish vaqti')),
                ('close_time', models.DateTimeField(verbose_name='Yopilish vaqti')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.group', verbose_name='Test beriladigan guruh')),
            ],
            options={
                'verbose_name': 'Test jadvali',
                'verbose_name_plural': 'Test jadvallari',
                'ordering': ['open_time'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.testschedule', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('completion_time', models.DateTimeField(auto_now_add=True, verbose_name='Tugatish vaqti')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bahosi')),
                ('grade_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Bahoning rangi (HEX)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testschedule', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'unique_together': {('student', 'test')},
            },
        ),
    ]
