# Generated by Django 5.2.1 on 2025-05-28 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_answeroption_testschedule_question_test_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testschedule',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AddField(
            model_name='question',
            name='test_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.testschedule'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='answer_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='tests.question'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='resit_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='completion_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='grade_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.testschedule'),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='close_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_schedules', to='tests.group'),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='num_questions',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='open_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='test_pdfs/'),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
