# Generated by Django 5.2.1 on 2025-05-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_answeroption_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testschedule',
            name='pdf_file',
        ),
    ]
